= Connect Simple ToDo App

image:https://api.travis-ci.com/ClearPointNZ/connect-simple-todo-java.svg?branch=master[caption="Travis Build Status"]

== Description
This is a simple todo microservice written in Java. The core of the application is extremely simple, but the
intention is to show the use of an app that

- exposes open tracing,
- links tracing to logs,
- exposes metrics for prometheus
- uses a feature toggle service
- has a feature in progress and it is testable by the FT service

It also shows how
- a proper Maven reactor build should work in CD environment,
- separation of dependencies for ease of consistency across your project
- Maven being able to provide reliable node 

This example application is using Java 11.  

== Installation Instructions

This project requires you to have Java 11 as your primary Java and Maven 3.5 or later installed.

- Java 11 should be downloaded from https://adoptopenjdk.net/ (do not download it from Oracle)


==== Java 11 on Mac OS X

This downloads as a gziped tar file, so extract the folder, and move it to `/Library/Java/JavaVirtualMachines` but ensure
you tack a `.jdk` on the end, so `jdk-11.0.2+9` becomes  `/Library/Java/JavaVirtualMachines/jdk-11.0.2+9.jdk`. 
Then set the environment variable JAVA_HOME to that folder + /Contents/Home, i.e.

----
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
----

This will cause the installed 'java' to swap to that version. Type `java -version` to confirm it has changed.

== Building from the command line

Just type `mvn clean install` and it should build everything, including the Docker ready
tar file (see below).  

== Application Structure

- todo-api contains the swagger.yaml file and that is all.
- todo-backend contains the Jersey + Netty implementation. No extra dependency framework is used as HK2 which comes
with Jersey is good enough for our purposes. 
- composite-* - these contain pom.xml files that consist solely of dependencies. This isolates dependencies around
particular problems and makes them easy to depend on and upgrade across the board.
- todo-feature-service - TODO - will contain the feature service for the TODO app
- todo-tests-api - test the server via the API, these are CD style e2e tests
- todo-tests-ui - test the running app via the API, these are CD style e2e tests
- todo-frontend - this is a React frontend for the app. 

== Running inside the IDE

As various libraries require unfettered access to the JVM, you need to ensure your JVM
flags are:

`--add-exports java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true --add-opens java.base/java.nio=ALL-UNNAMED`

This is included in the Docker image build. 

== For completeness

- use maven to build and deploy the app into local k8s (single node cluster in Docker)
- use toolbox to build using jenkins

== Building

Build the reactor, it will build the todo-backend and generate a Docker image that can
be loaded into Docker with 

`docker load --input target/jib-image.tar`

run with: `docker run -p 127.0.0.1:8099:8099/tcp cdconnect/todo-backend:latest`

It uses Google's JIB for building the docker image so you can build it even if you don't
have docker installed. You cannot run it this way however.
